[template]
src   = "reload"
dest  = "/usr/local/bin/reload"
owner = "root"
group = "root"
mode  = "0755"
keys = [
  "/deis/controller",
  "/deis/chef",
]
check_cmd = "test -e {{ .src }}"
reload_cmd = "/usr/local/bin/reload"
